### ISSUE TITLE
Is it possible to set own slug strategy?

### ISSUE THREAD

**Issue by yariksav** [adonisjs/adonis-lucid-slugify#11]
Hi! Need possibility to register to Strategies own function. Thanks

**Comment by RomainLanz** [comment]
Duplicate of https://github.com/adonisjs/adonis-lucid-slugify/issues/9

**Comment by yariksav** [comment]
Sorry, @RomainLanz  but I suppose this issue is not duplication of #9 
I asked is it possible to register own strategy function, for example I need to assign slug depends of record id, like id=201, slug='0000000201', etc, this is possible only afterCreate record

**Comment by RomainLanz** [comment]
Have you checked the documentation about **Defining custom strategies**?
https://github.com/adonisjs/adonis-lucid-slugify#defining-custom-strategies-

**Comment by yariksav** [comment]
Thank you very much, @RomainLanz!

**Comment by yariksav** [comment]
Sorry, i've occasionally deleted previous comment, but It is still actual to have slug depends of record ID. It's possible only in afterCreate hook. If it not actual for this package - I've made this by hooks directly. Thank you again ;)
